### ISSUE TITLE
Discreet mode toggle acts weird

### ISSUE THREAD

**Issue by mvaivre** [alephium/mobile-wallet#192] opened 2023-08-25 07:17 UTC
Maybe something to be investigated deeper. I fear that this state change triggers many side effects, which could explain the delays and jumps we see in the following video:

https://github.com/alephium/mobile-wallet/assets/6715943/e7c0df37-3dc4-4bf9-b3a1-01db9ef12922

**Comment by nop33** [comment] 2023-08-28 06:25
I cannot reproduce that either on iOS or on Android. I did some investigation in the code base and I could not find something suspicious.

**Comment by nop33** [comment] 2023-09-25 14:32
Did you manage to reproduce this one? If not, shall we close it?

**Closed** 2023-10-02 08:42 UTC
Labels: bug, can't reproduce
