### ISSUE TITLE
Onboarding refinements

### ISSUE THREAD

**Issue by mvaivre** [alephium/mobile-wallet#183] opened 2023-08-15 12:33 UTC
This list is going to be updated as the testing phase go:

- [x] The layout lacks some structural elements (field boxes)
- [x] When importing a wallet (Scan), the flow gets stuck after setting the password, with infinite "Importing wallet" loading.
- [x] The password is visible
- [x] The keyboard sometimes messes with the content (iOS)

**Comment by nop33** [comment] 2023-08-15 14:32
Oops, sorry, just noticed that it's assigned to you. I solved the second point and made a WIP PR.

**Comment by nop33** [comment] 2023-09-25 17:03
>  When importing a wallet (Scan), the flow gets stuck after setting the password, with infinite "Importing wallet" loading.

I could not reproduce on android (can't test on iOS, need an iPhone to scan my screen)

Is it still the case that it's failing on iOS (in the latest feature branch)?

**Comment by mvaivre** [comment] 2023-09-26 05:12
Yes unfortunately, still happening. 

![IMG_1219](https://github.com/alephium/mobile-wallet/assets/6715943/e3cd6ef4-8a1d-4725-91bc-b5c297b77081)

The import process seems fine, but the loading screen doesn't go away.

**Comment by nop33** [comment] 2023-09-26 07:26
Thanks for reproducing. It seems to work fine on Android.

**Comment by nop33** [comment] 2023-09-26 12:58
I tried to fix this, let me know if it still happens in my latest PR

**Comment by nop33** [comment] 2023-09-27 08:12
>  When importing a wallet (Scan), the flow gets stuck after setting the password, with infinite "Importing wallet" loading.

@mvaivre I believe this was addressed now in https://github.com/alephium/mobile-wallet/commit/12f2f9f5674d375fbc23ad749cee07858d1a16fc, right?

**Closed** 2023-10-02 08:26 UTC
Labels: bug, enhancement
