### ISSUE TITLE
[Android] Scrolling behaves erratically

### ISSUE THREAD

**Issue by mvaivre** [alephium/mobile-wallet#237] opened 2023-09-22 14:08 UTC
For instance, I'm not able to scroll in the Send/Origin screen, when I'm trying to pull over the cards. The only way for me to scroll is to interact with the small area around the "Send" title 😬

**Comment by nop33** [comment] 2023-09-26 13:12
I cannot reproduce it on my Android phone, and neither on simulators. Are you sure this wasn't a dev glitch?

**Comment by nop33** [comment] 2023-10-16 20:11
I don't think this is the case anymore, I couldn't reproduce on any of my Android phones, nor the simulators. Closing. Feel free to open it again! :)

**Closed by nop33** 2023-10-16 20:11 UTC
Labels: bug
