### ISSUE TITLE
walletconnect/ actually signing stopped working

### ISSUE THREAD

**Issue by diomark** [alephium/mobile-wallet#383] opened 2023-11-26 18:02 UTC
Signing requests stopped working for me about a week ago.

Android/wallet connect / play store version / chrome browser (pixel 7 pro)

To replicate - use walletconnect to sign into (tested on ayin.app, deadrare.io, as well as walph.io)

Try to do an action requiring signing (i.e. BUY on deadrare or SWAP on ayin.app or buying a ticket on walph.io

Switch back to wallet. expectation is that the signing  request is there (actually expectation is that it would auto-switch to wallet to sign but I know that's a different issue you're working on) - but it's not:( signing is currently not working for me.

**Comment by nop33** [comment] 2023-11-27 04:18
Hey @diomark, we've moved out projects to a monorepo.

Duplicate of https://github.com/alephium/alephium-frontend/issues/110

**Closed as completed by nop33** 2023-11-27 04:18 UTC

**Comment by diomark** [comment] 2023-11-27 05:09
Thanks. In the future should users open mobile wallet issues on this github or alephium-frontend?  cheers, -m

**Comment by mvaivre** [comment] 2023-11-27 07:26
Issues related to any of the frontend app should now be submitted in the `alephium-frontend` repo :)
We will archive the old repos to avoid confusion!
