### ISSUE TITLE
Internal feedback - part 3

### ISSUE THREAD

**Issue by mvaivre** [alephium/mobile-wallet#301] opened 2023-10-09 08:39 UTC
- [x] On iOS 16.7, iPhone 13 mini, white screen happening after the app is put to background (swipe to another app and swipe back)
- [x] First time scanning for an address didn't work. Camera wasn't activated
- [ ] Infinite loading of some token (Beer token)
- [x] Wallet import: importing manually, then going back to the intro screen ("you are about to import a wallet"), then continuing again to the address scan page: cannot move forward.
- [x] Active address scan: make it clearer that the user needs to select the addresses to import.

**Comment by nop33** [comment] 2023-10-09 09:58
>  On iOS 16.7, iPhone 13 mini, white screen happening after the app is put to background (swipe to another app and swipe back)

Duplicate: https://github.com/alephium/mobile-wallet/issues/299

**Comment by nop33** [comment] 2023-10-09 16:29
>  Infinite loading of some token (Beer token)

Could not reproduce. Possibly a network error. How about creating a dedicated issue to improve the whole app experience when there are network errors? I think we can go with the initial release without this.

**Comment by nop33** [comment] 2023-10-10 13:25
>  First time scanning for an address didn't work. Camera wasn't activated

Addressed by https://github.com/alephium/mobile-wallet/pull/297/commits/033d0404c18dcf9577671c82fe9e0a141c288552

**Closed** 2023-10-10 16:59 UTC
Labels: bug, enhancement
